export const FETCH_QUIZES_START = 'FETCH_QUIZES_START';
export const FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS';
export const FETCH_QUIZES_ERROR = 'FETCH_QUIZES_ERROR';
export const FETCH_QUIZE_SUCCESS = 'FETCH_QUIZE_SUCCESS';

export const SET_QUIZ = 'SET_QUIZ';
export const NEXT_QUIZ = 'NEXT_QUIZ';
export const QUIZ_FINISHED = 'QUIZ_FINISHED';
export const RETRY_QUIZ = 'RETRY_QUIZ';


export const ADD_QUIZ_QUESTION  = 'ADD_QUIZ_QUESTION';
export const RESET_QUIZ_CREATION = 'RESET_QUIZ_CREATION';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const LOGOUT = 'LOGOUT';